s:18179:"
    <header>
        <h1>Pro Interview:  Alex Beadon Photography by Liesl Cheney</h1>
    </header>

    <div class="author-meta align-left wrap">

        <img alt='' src='http://0.gravatar.com/avatar/e3fc2252d07f8551b797d61e08a6fb2d?s=100&amp;d=http%3A%2F%2F0.gravatar.com%2Favatar%2Fad516503a11cd5ca435acc9bb6523536%3Fs%3D100&amp;r=G' class='avatar avatar-100 photo' height='100' width='100' />        <a href="http://tpp.loc/author/liesl">By: Liesl Cheney</a>
        <p>A wedding and portrait photographer based in Surrey with a love for capturing the most precious and fleeting moments and making them last forever.  I am extremely passionate about what I do and love nothing more than beautiful moments and making people smile.</p>

    </div>

    <div class="entry-content">
        <p><a href="http://www.thephotographyparlour.com/wp-content/uploads/2011/07/Alex-Beadon-by-Dominique-Bader-Photography.jpg"><img class="alignleft size-medium wp-image-5961" src="http://www.thephotographyparlour.com/wp-content/uploads/2011/07/Alex-Beadon-by-Dominique-Bader-Photography-199x300.jpg" alt="" width="199" height="300" /></a>I first met <a href="http://www.alexbeadonphotography.com/">Alex Beadon</a> earlier this year at <a href="http://www.swpp.co.uk/">SWPP</a>.  She is really warm, friendly and down to earth, not to mention extremely talented.  Alex is one of those people who is constantly pushing herself and thinking outside of the box.  She seems to be able to capture the beauty around her with ease and delight and her blog is plethora of inspiration and passion.  Alex is a portrait photographer based in the UK and is also very involved in <a href="http://www.shutterrock.jazampawfarr.com/#/home/">Shutterrock</a>.</p>
<p><strong>Hi Alex, thanks for joining us on The Photography Parlour!  Could you take a moment to tell us who you are and tell us three random facts about yourself?</strong></p>
<p>Hi Liesl! Thanks so much for having me! Ok, so my name is Alex Beadon and I&#8217;m a creative portrait photographer who is passionate about love, people, social media, photography, blogging and marketing.  Three random facts? 1) I have two passports – one from Trinidad and Tobago, the other from the United Kingdom. 2) I love Chipotle. 3) I hate salad fingers (Google it if you&#8217;re unsure).</p>
<p><a href="http://www.thephotographyparlour.com/wp-content/uploads/2011/07/Alex_Beadon_Photography_1.jpg"><img class="aligncenter size-full wp-image-5936" src="http://www.thephotographyparlour.com/wp-content/uploads/2011/07/Alex_Beadon_Photography_1.jpg" alt="" width="590" height="394" /></a></p>
<p><a href="http://www.thephotographyparlour.com/wp-content/uploads/2011/07/Alex_Beadon_Photography_2.jpg"><img class="aligncenter size-full wp-image-5937" src="http://www.thephotographyparlour.com/wp-content/uploads/2011/07/Alex_Beadon_Photography_2.jpg" alt="" width="590" height="394" /></a></p>
<p><strong>Having recently just graduated from university and gaining a degree in Management with Marketing, could you tell us how you found your way into photography and describe the journey so far?</strong></p>
<p>I got my first DSLR at the age of 18. I loved photography, but at the time it was just a hobby – it never even crossed my mind to study it at university.  So instead, I decided to study another passion of mine, Marketing.  During my first year of university I discovered the work of <a href="http://lauraferreira.com">Laura Ferreira</a> and <a href="http://www.jessicaclaire.net">Jessica Claire</a>.  I was so inspired by their work, and by the fact that they had managed to turn photography into a business!  I followed them online, particularly Jessica Claire – who posted on her blog regularly, and who I followed religiously.</p>
<p><a href="http://www.thephotographyparlour.com/wp-content/uploads/2011/07/Alex_Beadon_Photography_3.jpg"><img class="aligncenter size-full wp-image-5938" src="http://www.thephotographyparlour.com/wp-content/uploads/2011/07/Alex_Beadon_Photography_3.jpg" alt="" width="590" height="394" /></a></p>
<p>I soon discovered that there were more photographers like her out there, and managed to stumble upon other inspiring photographers such as <a href="http://www.sarahrhoads.com/#/special/splash/">Sarah Rhoads</a> and <a href="http://jasminestarblog.com/">Jasmine Star</a>.  At this point I was photographing all the time, anything and everything.  I was reading as many photography related articles online as possible, trying to teach myself as much as I possibly could.  It took up all of my time. The internet is an amazing resource with a never-ending amount of information, and I&#8217;m so grateful for it.  By the time I hit the beginning of my third year, it was very apparent to me that I wanted to be a photographer.  Deep down I had known it for a long time, but always felt too scared to say it out loud.  At this point I started blogging, and photographing as much as I could – which honestly at that stage wasn&#8217;t very much.  I think at the beginning of it all I was still too scared and hesitant about it to shoot as much as I wish I would have, plus I felt very trapped because most of my time at that stage was spent studying for my final exams.  Ever since graduating from university it has pretty much been a roller coaster ride, many ups and downs, but I&#8217;m loving it and soaking as much of it in as I possibly can.  I go to sleep so happy every single night, dying for it to be morning again so that I can get back to work, back to my photography.</p>
<p><a href="http://www.thephotographyparlour.com/wp-content/uploads/2011/07/Alex_Beadon_Photography_4.jpg"><img class="aligncenter size-full wp-image-5939" src="http://www.thephotographyparlour.com/wp-content/uploads/2011/07/Alex_Beadon_Photography_4.jpg" alt="" width="590" height="393" /></a></p>
<p>To be honest, I&#8217;m still trying to find my feet in this crazy world of photography.  At first, all I wanted to do was wedding photography, and now I&#8217;m focusing on my portrait photography and seeing where that leads me.  Who knows, maybe one day I will venture into the world of fashion, or even come back to weddings.</p>
<p><a href="http://www.thephotographyparlour.com/wp-content/uploads/2011/07/Alex_Beadon_Photography_5.jpg"><img class="aligncenter size-full wp-image-5940" src="http://www.thephotographyparlour.com/wp-content/uploads/2011/07/Alex_Beadon_Photography_5.jpg" alt="" width="590" height="393" /></a></p>
<p><strong>Where did you learn to take such amazing pictures?</strong></p>
<p>Photography is a beautiful thing because it is so individual.  Everyone learns in different ways and it makes our work so unique.  The internet has been my teacher.  All of the amazing photographers out there who give and give, who aren&#8217;t scared to share knowledge and information – they are the reason why I am where I am today.  However, I also owe it to my passion and my willingness and desire to shoot as much as possible.  Nothing beats learning from experience, no matter how much you learn online, it will all be useless unless you put it to practice and experiment.</p>
<p><a href="http://www.thephotographyparlour.com/wp-content/uploads/2011/07/Alex_Beadon_Photography_6.jpg"><img class="aligncenter size-full wp-image-5941" src="http://www.thephotographyparlour.com/wp-content/uploads/2011/07/Alex_Beadon_Photography_6.jpg" alt="" width="590" height="393" /></a></p>
<p><a href="http://www.thephotographyparlour.com/wp-content/uploads/2011/07/Alex_Beadon_Photography_7.jpg"><img class="aligncenter size-full wp-image-5942" src="http://www.thephotographyparlour.com/wp-content/uploads/2011/07/Alex_Beadon_Photography_7.jpg" alt="" width="590" height="394" /></a></p>
<p><strong>Have you been on any great courses recently that you can recommend to our readers?</strong></p>
<p>No, but I highly recommend <a href="http://www.ted.com/">TED</a>, <a href="http://danesanders.com/">Dane Sander&#8217;s </a>interviews, <a href="http://www.sethgodin.com/sg/">Seth Godin</a>, <a href="http://www.creativelive.com/">CreativeLive</a> (all very inspiring and educational).</p>
<p><a href="http://www.thephotographyparlour.com/wp-content/uploads/2011/07/Alex_Beadon_Photography_8.jpg"><img class="aligncenter size-full wp-image-5943" src="http://www.thephotographyparlour.com/wp-content/uploads/2011/07/Alex_Beadon_Photography_8.jpg" alt="" width="590" height="394" /></a></p>
<p><strong>How would you describe your style and approach to photography?</strong></p>
<p>My style and approach to photography is something that is constantly changing.  Right now I am in love with the creative aspect of it all.  Creating a story or a scene through a photograph that really connects with the viewer – makes them stop and stare – that&#8217;s my goal.  I don&#8217;t want to create something that is similar to something that has been done hundreds of times before.  I aim to create something that reflects something inside of me, maybe something that I&#8217;m feeling or can relate to, and simultaneously has the powerful ability to make people stop and stare.</p>
<p><a href="http://www.thephotographyparlour.com/wp-content/uploads/2011/07/Alex_Beadon_Photography_9.jpg"><img class="aligncenter size-full wp-image-5944" src="http://www.thephotographyparlour.com/wp-content/uploads/2011/07/Alex_Beadon_Photography_9.jpg" alt="" width="590" height="394" /></a></p>
<p>I always say, that if one of my photos comes onto your Facebook news feed, and catches your eye enough to encourage you to click on it and spend even ten seconds of your valuable time looking at it &#8211; then I&#8217;ve done my job.  Photography is fun in the creative aspect of it. Photography is necessary in the documenting aspect of it.  Photography is powerful in the artistic aspect of it.</p>
<p><a href="http://www.thephotographyparlour.com/wp-content/uploads/2011/07/Alex_Beadon_Photography_10.jpg"><img class="aligncenter size-full wp-image-5945" src="http://www.thephotographyparlour.com/wp-content/uploads/2011/07/Alex_Beadon_Photography_10.jpg" alt="" width="590" height="393" /></a></p>
<p><strong>Could you tell us more about how you go about building your network amongst your peers and how you manage these working relationships?</strong></p>
<p>Networking! I love it! I use Facebook, Twitter and my blog to build my network.  It has been so much fun and so rewarding – here are my two biggest tips:</p>
<p>1) Put yourself out there – If you don&#8217;t leave comments or get the conversation started, how could you ever expect anyone else to?</p>
<p>2) Be the best version of yourself – Be yourself, let that personality shine through, but try to avoid projecting negativity.</p>
<p><a href="http://www.thephotographyparlour.com/wp-content/uploads/2011/07/Alex_Beadon_Photography_11.jpg"><img class="aligncenter size-full wp-image-5948" src="http://www.thephotographyparlour.com/wp-content/uploads/2011/07/Alex_Beadon_Photography_11.jpg" alt="" width="590" height="393" /></a></p>
<p><strong>Alex you have done a few gorgeous creative shoots, could you tell us more about them and what inspired you to do them?</strong></p>
<p>At first my creative shoots were merely for the purpose of a creative outlet.  I didn&#8217;t think that I would enjoy them as much as I did, and I definitely didn&#8217;t think that they would inspire me to drop weddings altogether and become a portrait photographer, but they did, and I&#8217;m so happy that they did.  I was inspired to do them because I wanted to spread my wings a little bit.  I wanted to get out of my comfort zone.  I wanted to try something new and I loved it. When I am photographing someone, and interacting with them, and being creative I come to life.  Even if it&#8217;s cold outside I have to take my jacket off because I get hot and excited. I know that sounds crazy, but it&#8217;s what passion does to you. It makes two hours seem like five minutes. It makes you feel like you are doing what you are meant to be doing. I love creativity, I love portraits. What I&#8217;m doing now combines the two.</p>
<p><a href="http://www.thephotographyparlour.com/wp-content/uploads/2011/07/Alex_Beadon_Photography_12.jpg"><img class="aligncenter size-full wp-image-5949" src="http://www.thephotographyparlour.com/wp-content/uploads/2011/07/Alex_Beadon_Photography_12.jpg" alt="" width="590" height="394" /></a></p>
<p><strong>Who or what inspires you and your work?</strong></p>
<p>Oh my gosh. This question is always a tough one, so instead, I will pretend that you asked me who or what has inspired me today:  <a href="http://jamesmeliaphoto.com/">James Melia</a>,  <a href="http://www.petrovajulian.com/">Petrova Julian</a>, <a href="http://500px.com/alina_troeva">Alina Troeva</a>.  The gorgeous colours of summer, the wonderful textures that surround me and life&#8217;s simple pleasures. The book I&#8217;m reading (A New Earth by Eckhart Tolle). Music, feelings, and love.</p>
<p><a href="http://www.thephotographyparlour.com/wp-content/uploads/2011/07/Alex_Beadon_Photography_13.jpg"><img class="aligncenter size-full wp-image-5950" src="http://www.thephotographyparlour.com/wp-content/uploads/2011/07/Alex_Beadon_Photography_13.jpg" alt="" width="590" height="394" /></a></p>
<p><strong>What is your favourite online resource for inspiration that you think that TPP readers could benefit from?</strong></p>
<p><a href="http://www.shutterrock.jazampawfarr.com/#/home/">ShutterRock</a>!! An AMAZING community of photographers who go out of their way to share and support each other. I get inspiration from them every day.</p>
<p><a href="http://www.500px.com/">www.500px.com</a> – I love the beautiful art work featured there.</p>
<p><a href="http://www.creativelive.com">CreativeLive</a> – Such a wonderful resource</p>
<p><a href="http://www.thephotographyparlour.com/wp-content/uploads/2011/07/Alex_Beadon_Photography_14.jpg"><img class="aligncenter size-full wp-image-5951" src="http://www.thephotographyparlour.com/wp-content/uploads/2011/07/Alex_Beadon_Photography_14.jpg" alt="" width="590" height="393" /></a></p>
<p><strong>Are there any photographers whose work you particularly admire and follow?</strong></p>
<p>I used to be a huge blog stalker.  I couldn&#8217;t live without my Google reader.  Lately, I&#8217;ve let it slide.  At first it&#8217;s inspiring, but after a while it can be creatively stifling.  So I&#8217;ve stayed away from &#8220;following&#8221; people.  I do, however, click on anything that looks beautiful which pops up on any of my news feeds.  And I do spend some time every week to search blogs to see what people have been up to.  Do I follow anyone in particular? Not anymore.</p>
<p><a href="http://www.thephotographyparlour.com/wp-content/uploads/2011/07/Alex_Beadon_Photography_15.jpg"><img class="aligncenter size-full wp-image-5952" src="http://www.thephotographyparlour.com/wp-content/uploads/2011/07/Alex_Beadon_Photography_15.jpg" alt="" width="590" height="393" /></a></p>
<p><strong>What is on your list of things to achieve this year?</strong></p>
<p>Every day this year I want to do one significant thing that brings me closer to my dream. If I achieve this, then I will be very happy.</p>
<p><a href="http://www.thephotographyparlour.com/wp-content/uploads/2011/07/Alex_Beadon_Photography_17.jpg"><img class="aligncenter size-full wp-image-5954" src="http://www.thephotographyparlour.com/wp-content/uploads/2011/07/Alex_Beadon_Photography_17.jpg" alt="" width="590" height="394" /></a></p>
<p><strong>If someone said: How can I be the next Alex Beadon?  What would you say?</strong></p>
<p>You could never be the next me.  In the same way that Brad Pitt could never be the next Ben Stiller.  In the same way that Lady Gaga could never be the next Adele. You could never be me. I could never be you.  And I&#8217;m sure you have some pretty AMAZING qualities that I am incredibly jealous of and could never have.  Love who you are. Love yourself just the way you are. Never try to be anyone else.</p>
<p><a href="http://www.thephotographyparlour.com/wp-content/uploads/2011/07/Alex_Beadon_Photography_18.jpg"><img class="aligncenter size-full wp-image-5955" src="http://www.thephotographyparlour.com/wp-content/uploads/2011/07/Alex_Beadon_Photography_18.jpg" alt="" width="590" height="590" /></a></p>
<p>Try to be the best version of yourself and above all, stay true to yourself and to your photography. And BELIEVE in yourself, because if you don&#8217;t &#8211; how can you expect anyone else to? Carve your own path, and never aspire to be &#8220;the next&#8221; of anyone.</p>
<p><strong>Lastly, every photographer has a different love for photographing particular subjects whether its portraits, landscapes, shadows and lights – could you share two of your favourite non-wedding images with us and tell us what it is that draws you to them?</strong></p>
<p><strong><a href="http://www.thephotographyparlour.com/wp-content/uploads/2011/07/Alex-Beadon-Photography-21.jpg"><img class="aligncenter size-full wp-image-5956" src="http://www.thephotographyparlour.com/wp-content/uploads/2011/07/Alex-Beadon-Photography-21.jpg" alt="" width="590" height="590" /></a></strong></p>
<p><strong><a href="http://www.thephotographyparlour.com/wp-content/uploads/2011/07/Alex-Beadon-Photography-22.jpg"><img class="aligncenter size-full wp-image-5957" src="http://www.thephotographyparlour.com/wp-content/uploads/2011/07/Alex-Beadon-Photography-22.jpg" alt="" width="590" height="590" /></a></strong></p>
<p>Lately I have been loving iPhone photography! It has really simplified everything for me and brought me back to my original love for images. Creating beautiful images with my iphone reminds me that it&#8217;s not about the fancy camera or lens, it&#8217;s about you.</p>
<p><strong>A massive thank you to Alex for the interview.  Be sure to stop by Alex’s <a href="http://www.alexbeadonphotography.com/">website</a> and <a href="http://www.alexbeadonphotography.com/blog/">blog </a>to view more of her work.</strong></p>
    </div>

        ";