s:16941:"
    <header>
        <h1>Pro Interview: An interview with Mike Larson by Vinita Salome</h1>
    </header>

    <div class="author-meta align-left wrap">

        <img alt='' src='http://0.gravatar.com/avatar/8525b4cfd01ccbf97dc70eba815e5fe3?s=100&amp;d=http%3A%2F%2F0.gravatar.com%2Favatar%2Fad516503a11cd5ca435acc9bb6523536%3Fs%3D100&amp;r=G' class='avatar avatar-100 photo' height='100' width='100' />        <a href="http://tpp.loc/author/vinita">By: Vinita Salome</a>
        <p>Vinita is a natural light contemporary photographer specialising in lifestyle portrait photography for families and children. She endeavours to capture the invisible ties connecting people.</p>

    </div>

    <div class="entry-content">
        <p><a href="http://www.thephotographyparlour.com/wp-content/uploads/2011/08/Mike-18.jpg"><img class="alignleft size-medium wp-image-6175" src="http://www.thephotographyparlour.com/wp-content/uploads/2011/08/Mike-18-240x300.jpg" alt="" width="240" height="300" /></a>Today I&#8217;d like to welcome Mike Larson from Mike Larson Photographer Inc. Mike is an Estate and Vineyard Wedding Photographer.  Having been to one of Mike’s workshop I can say Mike is a generous and adventurous soul who is also committed to seeing his workshop attendees succeed in their line of work.</p>
<p>Enjoy the in-depth interview with Mike and share your thoughts in the comments section below.</p>
<p>&nbsp;</p>
<p><strong>Tell us a little about yourself. Where are you from and  what is your style of photography?</strong></p>
<p>Hi! My name is Mike Larson, and I&#8217;m an Estate &amp; Vineyard wedding photographer from San Luis Obispo California, located in wine country on the coast.  I specialize in shooting weddings at private estates and vineyards only for the discerning couple. Estate &amp; vineyard weddings are a blend of celebration, intimacy and unique character drawn from this historic countryside wine region.  Warm sunsets, the smell of oak trees, amazing wine and extraordinary culinary treats, luxuriously enjoyed with a close circle of family and friends, creates a truly incredible wedding event.  For the last 10 years, I have been passionate about capturing these intimate events at estates and vineyards and look forward to getting to know and serve you on this most amazing day of your life.  I shoot mostly outdoors.</p>
<p>Personally, I am passionate about family, down time with them, including my wife and baby girl.  I love to cook and am inspired by Thomas Keller, whose meals you would find if you came over to the many dinner nights I host at my house.  I am avid traveller and love exploring the world.  I&#8217;m a teacher at heart and love mentoring those younger than me as I&#8217;ve been blessed with mentors who&#8217;ve poured into me.</p>
<p><a href="http://www.thephotographyparlour.com/wp-content/uploads/2011/08/Mike.jpg"><img class="aligncenter size-full wp-image-6198" src="http://www.thephotographyparlour.com/wp-content/uploads/2011/08/Mike.jpg" alt="" width="590" height="421" /></a><strong>Can you tell us a little bit about your journey into photography? Was there a special moment when you thought you wanted to delve into this subject?</strong></p>
<p>It’s all I&#8217;ve ever done.  I was captivated by Ansel Adams in 1996 and shot landscapes until 1998, weddings from 98 until 2002.  I was a surf photographer &amp; shot advertising campaigns from 02-05 and a wedding photographer only from 05 until present.  I&#8217;ve grown a lot over the last decade and been forever changed by the experiences I&#8217;ve seen while shooting, blessed by the travel opportunities, grown through the high expectations of the advertising world and honored by those who&#8217;ve commissioned me to capture a families most intimate and important day of their life.</p>
<p><a href="http://www.thephotographyparlour.com/wp-content/uploads/2011/08/Mike-2.jpg"><img class="aligncenter size-full wp-image-6182" src="http://www.thephotographyparlour.com/wp-content/uploads/2011/08/Mike-2.jpg" alt="" width="590" height="421" /></a><strong>Can you tell us what inspires you or what influences you in your work?</strong></p>
<p>I am most inspired by the amazing locations, the history, architecture, and capturing these unique elements that surround an even more unique couple.  I do believe that the experience my couples have, is just as important if not more as the images in the end.  What I add, quietly observe, and how I lead during an event is very important that its exactly what the couple anticipates and expects.  This is an endless skill to be perfected.</p>
<p><a href="http://www.thephotographyparlour.com/wp-content/uploads/2011/08/Mike-3.jpg"><img class="aligncenter size-full wp-image-6183" src="http://www.thephotographyparlour.com/wp-content/uploads/2011/08/Mike-3.jpg" alt="" width="590" height="421" /></a><strong>What gear do you use and what are your favourite lenses?  If you are limited to one lens, which one would you use and why?</strong></p>
<p>I&#8217;m a Canon guy 100%, and my favorite lens is my 50mm 1.2. It’s the most diverse and its exactly what the eye sees.  I love the shallow depth of field.  It’s good enough for portraits but also allows me to get back and still include background if I wanted a wider perspective.  Great in low light as well!</p>
<p><a href="http://www.thephotographyparlour.com/wp-content/uploads/2011/08/Mike-4.jpg"><img class="aligncenter size-full wp-image-6184" src="http://www.thephotographyparlour.com/wp-content/uploads/2011/08/Mike-4.jpg" alt="" width="590" height="421" /></a><strong>Can you share with us your favourite photographers and their websites/blogs?</strong></p>
<p>My favorite photographers are my friends <a href="http://www.josevillaphoto.com/">Jose Villa,</a> I love his work and the consistency of his style and messaging.  I am inspired by my friend <a href="http://www.mikecolon.com/">Mike Colon</a> with his dedication to working and networking with the specific type of clientèle he wants.  He truly gives a world class service to his couples.</p>
<p><a href="http://www.thephotographyparlour.com/wp-content/uploads/2011/08/Mike-5.jpg"><img class="aligncenter size-full wp-image-6185" src="http://www.thephotographyparlour.com/wp-content/uploads/2011/08/Mike-5.jpg" alt="" width="590" height="421" /></a><strong>What is the most stressful shooting situation you have comes across and how did you solve it?</strong></p>
<p>I had a camera go out on me during a wedding in Singapore and had to tweet out to get another backup, and someone came to the rescue and loaned us one.  Thankful for friends in all the corners of the globe!</p>
<p><a href="http://www.thephotographyparlour.com/wp-content/uploads/2011/08/Mike-6.jpg"><img class="aligncenter size-full wp-image-6186" src="http://www.thephotographyparlour.com/wp-content/uploads/2011/08/Mike-6.jpg" alt="" width="590" height="421" /></a><strong>Have you attended any workshops since you started giving them? If yes, which one and why? If no, why?</strong></p>
<p>Yes, I&#8217;ve recently been attending business workshops.  I&#8217;ve spent over $15,000 in the last 2-3 years growing the back end of what I do so that I&#8217;m sustainable long term.  I&#8217;ve met too many people who have gotten burned out of their passion because they were not profitable enough.  In the end, I think a photographer needs to be a businessperson who is passionate about photography.  If you are weak on the business side, you don&#8217;t have as good of a chance of becoming both great, and profitable.</p>
<p><a href="http://www.thephotographyparlour.com/wp-content/uploads/2011/08/Mike-7.jpg"><img class="aligncenter size-full wp-image-6187" src="http://www.thephotographyparlour.com/wp-content/uploads/2011/08/Mike-7.jpg" alt="" width="590" height="393" /></a><strong>Do you have a photography mentor/guru? If yes who? Does their style influence you till today?</strong></p>
<p>Yes, but I don&#8217;t think it is fair to just have one!  Spread around the load of the questions we all have.  For different reasons I seek out the following:  Jeff Jochum (<a href="http://startup-strategy.com/">startup-strategy.com</a>) &amp; Kevin Swan (<a href="http://f22marketing.com/">f22marketing.com</a>) for their marketing &amp; business advice.  They have radically influenced my business.  Imaging wise, Jose Villa (<a href="http://josevillaphoto.com/">josevillaphoto.com</a>), and my buddy Cameron Ingalls (<a href="http://cameroningalls.com/">cameroningalls.com</a>).  All of these people are friends and I&#8217;m thankful for them.  I have other personal advisors who will go unnamed.</p>
<p><a href="http://www.thephotographyparlour.com/wp-content/uploads/2011/08/Mike-8.jpg"><img class="aligncenter size-full wp-image-6188" src="http://www.thephotographyparlour.com/wp-content/uploads/2011/08/Mike-8.jpg" alt="" width="590" height="443" /></a><strong>Can you tell us a little bit about the transition from a photographer working alone to having associates?</strong></p>
<p>I&#8217;d recommend always getting the right people before you jump into associates.  Find a career associate rather than a transient one.  Pour into them and grow them.  Your value to them will be their loyalty.  I&#8217;d also highly recommend splitting brands if you want a boutique brand and them to be a lower cost alternative.  If you want to have them as equals, than its ok to just have them work alongside you and your name.</p>
<p><a href="http://www.thephotographyparlour.com/wp-content/uploads/2011/08/Mike-9.jpg"><img class="aligncenter size-full wp-image-6189" src="http://www.thephotographyparlour.com/wp-content/uploads/2011/08/Mike-9.jpg" alt="" width="590" height="421" /></a><strong>What mistake have you made in your business that haunts you till today?</strong></p>
<p>The biggest mistake I make is not executing what I should when I have it down as a goal.  I&#8217;m not a huge procrastinator, but I highly recommend having accountability when it comes to executing your goals within a time frame!  I also wish I would have specialized into what I&#8217;m doing now, 2-3 years earlier.</p>
<p><a href="http://www.thephotographyparlour.com/wp-content/uploads/2011/08/MIke-10.jpg"><img class="aligncenter size-full wp-image-6190" src="http://www.thephotographyparlour.com/wp-content/uploads/2011/08/MIke-10.jpg" alt="" width="590" height="421" /></a><strong>What are your indulgences?</strong></p>
<p>Food!  I&#8217;m a foodie. I love cooking and sharing good food with friends.  I also love surfing and travel.</p>
<p><a href="http://www.thephotographyparlour.com/wp-content/uploads/2011/08/MIke-11.jpg"><img class="aligncenter size-full wp-image-6191" src="http://www.thephotographyparlour.com/wp-content/uploads/2011/08/MIke-11.jpg" alt="" width="590" height="421" /></a><strong>What is the influence Hannah (your daughter of six months) has had on your photography?</strong></p>
<p>She reminds me even more that my most favorite shoots are not the posed ones, but the real life ones.  See attached</p>
<p><a href="http://www.thephotographyparlour.com/wp-content/uploads/2011/08/Mike-15.jpg"><img class="aligncenter size-full wp-image-6195" src="http://www.thephotographyparlour.com/wp-content/uploads/2011/08/Mike-15.jpg" alt="" width="590" height="590" /></a><a href="http://www.thephotographyparlour.com/wp-content/uploads/2011/08/Mike-16.jpg"><img class="aligncenter size-full wp-image-6196" src="http://www.thephotographyparlour.com/wp-content/uploads/2011/08/Mike-16.jpg" alt="" width="590" height="590" /></a><strong>You are very open about your faith and how it fuels you to become a better person and photographer.  Have you always been this open? If not, what lead you to it?</strong></p>
<p>I&#8217;ve grown less ashamed.  It is what I&#8217;m most passionate about.  In the end I believe in an eternity with God or without.  The gospel and what Jesus did for me gives me freedom from my mistakes and errors and character flaws.  He miraculously changes me.  If you were to put me on trial and run video of who  I was inside before and after, you&#8217;d have to conclude that the evidence shows that my relationship with my God has made me who I am.  Freedom from all the junk that could drag me down and giving me a joy that surpasses all understanding.  I wish that clarity and freedom upon everyone.</p>
<p><a href="http://www.thephotographyparlour.com/wp-content/uploads/2011/08/MIke-12.jpg"><img class="aligncenter size-full wp-image-6192" src="http://www.thephotographyparlour.com/wp-content/uploads/2011/08/MIke-12.jpg" alt="" width="590" height="421" /></a><strong>What do you see yourself doing five years from now?</strong></p>
<p>The same thing I am doing now, but I hope to be positioned to be the most well-known and sought after photographer for private estate weddings everywhere in the world.</p>
<p><a href="http://www.thephotographyparlour.com/wp-content/uploads/2011/08/MIke-13.jpg"><img class="aligncenter size-full wp-image-6193" src="http://www.thephotographyparlour.com/wp-content/uploads/2011/08/MIke-13.jpg" alt="" width="590" height="419" /></a><strong>What would be your ultimate goal in life?</strong></p>
<p>Business wise, (see above), personally to be faithful to my God, a successful family man, and a teacher to others.  Oh and to master making butternut squash gniochi from scratch! <img src="http://tpp.loc/wp-includes/images/smilies/icon_smile.gif" alt=":)" class="wp-smiley" /> </p>
<p><a href="http://www.thephotographyparlour.com/wp-content/uploads/2011/08/Mike.jpg"><img class="aligncenter size-full wp-image-6198" src="http://www.thephotographyparlour.com/wp-content/uploads/2011/08/Mike.jpg" alt="" width="590" height="421" /></a><strong>Do you see yourself changing the world with your art/work?</strong></p>
<p>Yes, I also hope to continue to empower my couples and any couple to focus on viewing their marriage and love as a daily choice. A commitment for life. This has such a HUGE effect on the kids, the family, our neighborhoods and our culture.  When the family breaks down, our culture will result in decay.  I believe that God has a purpose for growing our character through our marriage and kids.  For us to take ownership of who we were created to be.  Unique individual people producing what we&#8217;ve been skilled in, and serving others with a joyful heart, and giving to others.</p>
<p><a href="http://www.thephotographyparlour.com/wp-content/uploads/2011/08/Mike1.jpg"><img class="aligncenter size-full wp-image-6202" src="http://www.thephotographyparlour.com/wp-content/uploads/2011/08/Mike1.jpg" alt="" width="590" height="421" /></a></p>
<p><strong>Parting Story:</strong> (funny)</p>
<p>Years ago, I was teaching my 1st associate (Anna) to shoot weddings on her own, and she was very nervous, after finally getting her 1st wedding, it just so happened that my other client cancelled that day.  Anna wanted me to join her and help on her shoot, but I knew that she needed to shoot her 1st wedding on her own eventually, so reluctantly I agreed to come, but to stay in the car and let her shoot.  When we arrived at the location, the only place to park was right near the ceremony site so I had to hide somehow.  During the shoot, Anna, my associate, about every 10-20 minutes, would get stuck and forget camera settings and then panic.  So she would proceed to tell the bride she needed grab some &#8220;other&#8221; gear from the car.  I had to hide under blankets to stay low profile and not have the bride wonder why I was not shooting as well that day.  Anna would come in the car and pass the camera back to me under the blanket while trying to shield her mouth so it didn&#8217;t look like she was asking me a question.  I&#8217;d hear her, and adjust the camera or tell her what she needed to do to solve whatever problem came up.  This happened about 4-5 times the rest of the day.  She was nervous then and upset that I didn&#8217;t just shoot with her.  In the end, she grew from the experience and now shoots weddings on her own.  I&#8217;m proud of her.  Despite sweating and overheating in the back of the car under the blanket, we all laugh about that experience now.</p>
<p>Thank you for interviewing me.</p>
<p>ETA:</p>
<p>Mike Larson&#8217;s next Italian workshop has just been released and will be this September 20-21st a the same rustic Italian Villa in the heart of Tuscany.  For more details check out <a href="http://fallitalystyleshop.eventbrite.com/">http://fallitalystyleshop.eventbrite.com/</a> or <a href="http://www.mikelarson.com/seminars">http://www.mikelarson.com/seminars</a></p>
<p><strong>Thank you so much Mike for sharing so generously. To see more of Mike&#8217;s work please visit his <a href="http://www.mikelarson.com/">website .<br />
</a></strong></p>
    </div>

        ";